name: Publish

on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Moving build to artifacts directory
        run: |
          echo "Import the GPG key"
          echo  ${{ secrets.GITHUB_GPG_KEY }} | base64 -d > private.key
          gpg --import ./private.key
          rm ./private.key

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"

          maven-repo-server-id: ${{ secrets.MVN_REPO_PRIVATE_REPO_ID }}
          maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
          maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@minidigger.me"

          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

          maven-args: ${{ join('-Dgpg.passphrase=', secrets.MVN_REPO_PRIVATE_REPO_PASSWORD) }}
